-- Temporary scaffold placeholder schema.
-- This sample_items table is starter example data only and is not part of the
-- planned mango-mdu-service domain model.

CREATE TABLE IF NOT EXISTS sample_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert a default sample item if not exists
INSERT INTO sample_items (name, description)
VALUES ('Scaffold Placeholder', 'This is a sample item generated by the database bootstrap script.')
ON CONFLICT DO NOTHING;
